In [46]:
# Import necessary libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
sns.set(style='darkgrid')

In [47]:
data = pd.read_csv('AdvertAndSales.csv')
data.head()

     TV      Radio  Social Media Influencer       Sales
0  16.0   6.566231      2.907983       Mega   54.732757
1  13.0   9.237765      2.409567       Mega   46.677897
2  41.0  15.886446      2.913410       Mega  150.177829
3  83.0  30.020028      6.922304       Mega  298.246340
4  15.0   8.437408      1.405998      Micro   56.594181

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TV            4562 non-null   float64
 1   Radio         4568 non-null   float64
 2   Social Media  4566 non-null   float64
 3   Influencer    4572 non-null   object
 4   Sales         4566 non-null   float64
dtypes: float64(4), object(1)
memory usage: 178.7+ KB

In [49]:
data.describe()

                TV        Radio  Social Media        Sales
count  4562.000000  4568.000000   4566.000000  4566.000000
mean     54.066857    18.160356      3.323956   192.466602
std      26.125054     9.676958      2.212670    93.133092
min      10.000000     0.000684      0.000031    31.199409
25%      32.000000    10.525957      1.527849   112.322882
50%      53.000000    17.859513      3.055565   189.231172
75%      77.000000    25.649730      4.807558   272.507922
max     100.000000    48.871161     13.981662   364.079751

In [50]:
data.isnull().sum()

TV              10
Radio            4
Social Media     6
Influencer       0
Sales            6
dtype: int64

In [51]:
data= data.dropna()

In [52]:
data.isnull().sum()

TV              0
Radio           0
Social Media    0
Influencer      0
Sales           0
dtype: int64

In [53]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
import joblib

df = data.copy()

for i in df.drop('Sales', axis=1):
  if i in df.select_dtypes(include = 'number').columns:
    scaler = StandardScaler()
    df[i] = scaler.fit_transform(df[[i]])
    joblib.dump(scaler, open(f'{i}_scaler.pkl','wb'))
  else:
    encoder = LabelEncoder()
    df[i] = encoder.fit_transform(df[i])
    joblib.dump(encoder, open(f'{i}_encoder.pkl','wb'))

df.head()

         TV     Radio  Social Media  Influencer       Sales
0 -1.458233 -1.199655     -0.187919           1   54.732757
1 -1.573167 -0.923162     -0.413343           1   46.677897
2 -0.500455 -0.235049     -0.185464           1  150.177829
3  1.108613  1.227722      1.627686           1  298.246340
4 -1.496545 -1.005995     -0.867239           2   56.594181

In [56]:
x = df.drop('Sales', axis=1)
y = df['Sales']

from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size = 0.2, random_state=40)

In [57]:
from sklearn.linear_model import LinearRegression   # use to train the model
from sklearn.metrics import r2_score    # use for evaluation

model = LinearRegression()
model.fit(xtrain, ytrain)

model

LinearRegression()

In [58]:
validate = model.predict(xtrain)
print(f'model cross validation is : {round (r2_score(ytrain, validate)*100, 2)}')

pred = model.predict(xtest)
print(f'model performance is : {round (r2_score(ytest, pred)*100, 2)}')

model cross validation is : 99.9
model performance is : 99.9

In [ ]:
# To export the model
joblib.dump(model, open('advertmodel.pkl','wb'))